### ISSUE TITLE
about questions

### ISSUE THREAD

**Issue by liuliAI** [chancharikmitra/CCoT#1]
How to determine whether a person is "catching a frisbee" or "throwing a frisbee" in the generation of scene graphs ，the final answer depends on this logic.

**Comment by chancharikmitra** [comment]
Hello, @liuliAI! Thanks for your interest in our work. I believe you are referring to an older version of our figure. But regardless, if I am understanding your question correctly, you are asking how exactly the scene graph would contain information about the question or task being asked. 

So a few things. In compositional reasoning, we typically view images as a complex combination of objects, _attributes, and relationships,_ which can be described in a scene graph of an image.

Many VLMs see images only as a bag of objects. In this case, you are absolutely correct. A "bag-of-objects" model like CLIP would not be able to know whether a person is "throwing" or "catching" a frisbee as that involves understanding the relationship between the two. Now, in our method, because we **pass the image and task when generating the scene graph (SG)**, the generated SG is conditioned on the task, so we would expect the scene graph to contain helpful attribute and relationship information like "throwing" or "catching" to help the model reason compositionally about the image. Now, how _exactly_ the model does this is an interesting question we would love to see more future work on. From our experiments, it seems that the model has some latent compositional understanding of the image that we are able to extract using our zero-shot prompting method. 

Hope this clarifies!
