### ISSUE TITLE
Reproduce the result

### ISSUE THREAD

**Issue by ChengJade** [chancharikmitra/CCoT#11]
Thanks for your work. It is interesting, unfortunately, when i try to reproduce the work based on llava-v1.5-13b, there are some problems, 
Traceback (most recent call last):
  File "llava_whoops.py", line 87, in <module>
    pred_ans = get_ans(question, image_tensor)
  File "llava_whoops.py", line 68, in get_ans
    n_diff_input_output = (input_ids != output_ids[:, :input_token_len]).sum().item()
RuntimeError: The size of tensor a (205) must match the size of tensor b (15) at non-singleton dimension 1, i noticed it is different from the llava's original inference, if i replace it with the original way, it works, but can't reproduce the result mentioned in the paper. Did i skip something import, really appreciate it if you can help me with that!

Thanks!

**Comment by chancharikmitra** [comment]
Hello! Thank you for your interest in our work.

Although I am not 100% sure, there was a similar error posted here recently with LLaVA-1.5-13B. Since the release of our work, LLaVA-1.5 released updated scripts with its NeXT update (even for the 1.5 series of models). This means that the sample code we have is potentially not fully compatiable with the new codebase.

My suggestion would be to replicate our two prompts. The exact prompts are shown in Figure 2 of the paper. The only thing that will be different is the generated scene graph. We hope that our work can serve as the conceptual basis for the prompt you end up using (feel free to do prompt engineering!). The exact code from our repository is not necessary. Herein lies the flexibility of our work.

If you continue to run into issues just using the current LLaVA codebase, I would recommend asking their for the best support.

Hope this helps!
