### ISSUE TITLE
The LLaVA evaluation code is broken

### ISSUE THREAD

**Issue by littlepenguin89106** [chancharikmitra/CCoT#2]
I evaluate the CCoT with LLaVA1.5-13B on SEED-Bench.
However, in [the implementation](https://github.com/chancharikmitra/CCoT/blob/f8aed85cc0949b86e840122290eb488db83ce46d/LLaVA-1.5-13b/LLaVA_SEED.py#L202), I found `n_diff_input_output` always larger than 0, and `output_ids[:, :input_token_len]` is not a complete sentence, maybe it should use full `output_ids` instead of slicing?

**Comment by chancharikmitra** [comment]
Hi, the issue deals with the fact that since the update with LLaVA-1.6, the way `n_diff_input_output` is handled is different. Our scripts were from before this update. So there are two options here:

1. Use a version of the LLaVA model/codebase before the update.
2. Use our prompts and parameter settings as closely as possible with the new code post LLaVA-1.6 update.

Hope this helps!
