### ISSUE TITLE
evaluation process on the Winoground dataset 

### ISSUE THREAD

**Issue by aidialogue** [chancharikmitra/CCoT#3]
1.  I encountered a RuntimeError when running llava wino.py:
 n_diff_input_output = (input_ids != output_ids[:, :input_token_len]).sum().item()      
"The size of tensor a (195) must match the size of tensor b (168) at non-singleton dimension 1".    How can I resolve this issue?
2. Are the evaluation scores for models like LLaVA-1.5-13B-CCoT, Sphinx-CCoT, and InstructBLIP-13B-CCoT on the Winoground dataset determined by using the GPT-4 API to return the most matching explanations? Thank you for clarifying.
3. Are all temperature settings set to zero? I noticed that in InstructBLIP_MMBench.py, the temperature is set to 1.
4. while running InstructBLIP_MMBench.py, after inferring several hundred data entries, an error occurs: 
 embeddings = embeddings + position_embeddings
RuntimeError: The size of tensor a (533) must match the size of tensor b (512) at non-singleton dimension 1
This situation require changing max_position_embeddings to 1024, but the original model weights are set to 512. Have you encountered this issue before? Could you give me some appropriate advice, please? Thank you.

**Comment by chancharikmitra** [comment]
Hello! Thanks for your interest in our work. Sorry for the delayed response, but most of the team is at CVPR right now. 

1. Yes, this issue is likely because you are using the LLaVA-1.6 version of the codebase (which also changes the way 1.5 inputs are processed). The way the embeddings are handled is a bit different, so one way to handle this issue would be to try a version of LLaVA-1.5 before the LLaVA-1.6 update. For context, a similar issue was reported [here](https://github.com/chancharikmitra/CCoT/issues/2).
2. Yes, that's true.
3. In general, we try to match the generation parameters mentioned in each of the individual works. This is perhaps why it was set to 1. But intuitively 0 does make sense. Empirically, we find not too much difference in results.
4. There are few large images in mmbench that are inappropriate for InstructBLIP. For your use, we recommend skipping them.

Hope this helps!
